# Generated by Django 4.2.7 on 2023-12-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tiendaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccionTienda', models.CharField(blank=True, max_length=32, null=True)),
                ('provinciaTienda', models.CharField(blank=True, max_length=32, null=True)),
                ('regionTienda', models.CharField(blank=True, max_length=32, null=True)),
                ('fechaCreacionTienda', models.CharField(blank=True, max_length=32, null=True)),
                ('telefonoContactoTienda', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionProducto', models.CharField(blank=True, max_length=100, null=True)),
                ('codigoProducto', models.CharField(blank=True, max_length=32, null=True)),
                ('pvProducto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidadProducto', models.IntegerField()),
                ('tiendaRelacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionTienda.tiendainfo')),
            ],
        ),
    ]
