# Generated by Django 4.2.7 on 2023-12-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendainfo',
            name='nombreTienda',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
